name: past_question_paper_stem
description: "Past Question Paper STEM application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  image_picker: ^1.0.7
  path: ^1.8.3
  uuid: ^4.3.3
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  app_links: ^6.4.0
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Uncomment and add your assets here when needed
  # assets:
  #   - images/
  
  # Uncomment and add your fonts here when needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
