// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSxz-doRd7dKPRWOHH7-w2bkWZdWNeVqs',
    appId: '1:304255065963:web:ef29b8260fce36503eb62e',
    messagingSenderId: '304255065963',
    projectId: 'vibe-code-4c59f',
    authDomain: 'vibe-code-4c59f.firebaseapp.com',
    storageBucket: 'vibe-code-4c59f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Z4X_7NsN9HNfvsTSZhoCrsyJhZDMWh4',
    appId: '1:304255065963:android:548f4ad3bbeda6283eb62e',
    messagingSenderId: '304255065963',
    projectId: 'vibe-code-4c59f',
    storageBucket: 'vibe-code-4c59f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnH8bzRH57-tdSSe_mv3R9Ec1u_TV9IIA',
    appId: '1:304255065963:ios:13b254d3f64077f73eb62e',
    messagingSenderId: '304255065963',
    projectId: 'vibe-code-4c59f',
    storageBucket: 'vibe-code-4c59f.firebasestorage.app',
    iosBundleId: 'com.example.pastQuestionPaperStem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnH8bzRH57-tdSSe_mv3R9Ec1u_TV9IIA',
    appId: '1:304255065963:ios:13b254d3f64077f73eb62e',
    messagingSenderId: '304255065963',
    projectId: 'vibe-code-4c59f',
    storageBucket: 'vibe-code-4c59f.firebasestorage.app',
    iosBundleId: 'com.example.pastQuestionPaperStem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSxz-doRd7dKPRWOHH7-w2bkWZdWNeVqs',
    appId: '1:304255065963:web:7dc2e3ba30a6abf23eb62e',
    messagingSenderId: '304255065963',
    projectId: 'vibe-code-4c59f',
    authDomain: 'vibe-code-4c59f.firebaseapp.com',
    storageBucket: 'vibe-code-4c59f.firebasestorage.app',
  );
}
